export const GET_PROJECTS_REQUEST = "GET_PROJECTS_REQUEST";
export const GET_PROJECTS_SUCCESS = "GET_PROJECTS_SUCCESS";
export const GET_PROJECTS_FAILURE = "GET_PROJECTS_FAILURE";

export const GET_PROJECTS_WITH_USER_REQUEST = "GET_PROJECTS_WITH_USER_REQUEST";
export const GET_PROJECTS_WITH_USER_SUCCESS = "GET_PROJECTS_WITH_USER_SUCCESS";
export const GET_PROJECTS_WITH_USER_FAILURE = "GET_PROJECTS_WITH_USER_FAILURE";
