all: mastermind_with_read.c  mastermind_with_scanf.c
	gcc -g -Wall -Wextra -Werror -o mastermind_with_read mastermind_with_read.c
	gcc -g -Wall -Wextra -Werror -o mastermind_with_scanf mastermind_with_scanf.c

clean:
	$(RM) mastermind_with_read
	$(RM) mastermind_with_scanf

fclean: clean
	rm -f $(TARGET)